// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/2bb5e510505f24f8221d6dc586ff49ee5f9ccbbf/js-md5/md5.d.ts
interface JQuery {
    md5(value: string): string;
    md5(value: Array<any>): string;
    md5(value: Uint8Array): string;
}

interface JQueryStatic {
    md5(value: string): string;
    md5(value: Array<any>): string;
    md5(value: Uint8Array): string;
}

interface md5 {
    (value: string): string;
    (value: Array<any>): string;
    (value: Uint8Array): string;
}

interface String {
    md5(value: string): string;
    md5(value: Array<any>): string;
    md5(value: Uint8Array): string;
}

declare module "js-md5" {
    export = md5;
}

declare var md5: md5;
